const db = {
  the: { phones: ['DH', 'AH'] },
  of: { phones: ['AH', 'V'] },
  and: { phones: ['AH', 'N', 'D'] },
  to: { phones: ['T', 'UW'] },
  a: { phones: ['AH'] },
  in: { phones: ['IH', 'N'] },
  for: { phones: ['F', 'AO', 'R'] },
  is: { phones: ['IH', 'Z'] },
  on: { phones: ['AA', 'N'] },
  that: { phones: ['DH', 'AE', 'T'] },
  by: { phones: ['B', 'AY'] },
  this: { phones: ['DH', 'IH', 'S'] },
  with: { phones: ['W', 'IH', 'DH'] },
  i: { phones: ['AY'] },
  you: { phones: ['Y', 'UW'] },
  it: { phones: ['IH', 'T'] },
  not: { phones: ['N', 'AA', 'T'] },
  or: { phones: ['AO', 'R'] },
  be: { phones: ['B', 'IY'] },
  are: { phones: ['AA', 'R'] },
  from: { phones: ['F', 'R', 'AH', 'M'] },
  at: { phones: ['AE', 'T'] },
  as: { phones: ['AE', 'Z'] },
  your: { phones: ['Y', 'AO', 'R'] },
  all: { phones: ['AO', 'L'] },
  have: { phones: ['HH', 'AE', 'V'] },
  new: { phones: ['N', 'UW'] },
  more: { phones: ['M', 'AO', 'R'] },
  an: { phones: ['AE', 'N'] },
  was: { phones: ['W', 'AA', 'Z'] },
  we: { phones: ['W', 'IY'] },
};
export default db;